---
# Source: discourse/templates/secrets-discourse.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-discourse-discourse
  namespace: default
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: discourse
    app.kubernetes.io/version: 3.4.3
    helm.sh/chart: discourse-16.0.0
type: Opaque
data:
  discourse-password: "WHNKaEFjbzFZYw=="
